/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author HimelSaha
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() throws ScriptException {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        jTextArea1.setText("0");
        this.setTitle("Calculator");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlusMinus = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnReciprocal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnPercent = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBackSpace = new javax.swing.JButton();
        btnBrackets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlusMinus.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnPlusMinus.setText("± ");
        btnPlusMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMinusMouseClicked(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDot.setText(".");
        btnDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDotMouseClicked(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(51, 153, 255));
        btn0.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn0.setText("0 ");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnEqual.setBackground(new java.awt.Color(255, 102, 102));
        btnEqual.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnEqual.setText("= ");
        btnEqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqualMouseClicked(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(51, 153, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn1.setText("1 ");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(51, 153, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn2.setText("2 ");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(51, 153, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn3.setText("3 ");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(255, 102, 102));
        btnPlus.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnPlus.setText("+ ");
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMouseClicked(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 153, 255));
        btn4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn4.setText("4 ");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 153, 255));
        btn5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn5.setText("5 ");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(51, 153, 255));
        btn6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn6.setText("6 ");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        btnMinus.setBackground(new java.awt.Color(255, 102, 102));
        btnMinus.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnMinus.setText("- ");
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusMouseClicked(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(51, 153, 255));
        btn7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn7.setText("7 ");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(51, 153, 255));
        btn8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn8.setText("8 ");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 153, 255));
        btn9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn9.setText("9 ");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(255, 102, 102));
        btnMultiply.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnMultiply.setText("x ");
        btnMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplyMouseClicked(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(255, 102, 102));
        btnDivision.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDivision.setText("÷ ");
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisionMouseClicked(evt);
            }
        });

        btnSqrt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnSqrt.setText("sqrt ");
        btnSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSqrtMouseClicked(evt);
            }
        });

        btnSquare.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnSquare.setText("x^2 ");
        btnSquare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSquareMouseClicked(evt);
            }
        });

        btnReciprocal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnReciprocal.setText("1/x ");
        btnReciprocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReciprocalMouseClicked(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 51, 51));
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        btnPercent.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnPercent.setText("% ");
        btnPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPercentMouseClicked(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 0, 51));
        btnClear.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        btnClear.setText("Clear ");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnBackSpace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBackSpace.setText("<--");
        btnBackSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackSpaceMouseClicked(evt);
            }
        });

        btnBrackets.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBrackets.setText("( ) ");
        btnBrackets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBracketsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReciprocal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBrackets, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReciprocal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrackets, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("2");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "2");
        }
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("3");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "3");
        }
    }//GEN-LAST:event_btn3MouseClicked

    private void btnEqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualMouseClicked

        // TODO add your handling code here:
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine eng = mgr.getEngineByName("JavaScript");
        String str = jTextArea1.getText();
        String toBeCalculated = null;
        try {
            if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '(') {
                String compute = jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1);
                toBeCalculated = compute;
                // =============================================== PERCENTAGE METHOD BELOW
                String x = compute;
                while (x.contains("%")) {
                    System.out.println("entered");
                    char[] dst = new char[x.length()];
                    x.getChars(0, x.length(), dst, 0);

                    int percentDetected = 0;
                    int variableDetected = 0;
                    int switchValue = 2;
                    String laterHalf = null;

                    for (int i = x.length() - 1; i >= 0; i--) {
                        if (dst[i] == '%') {
                            percentDetected = i;
                            laterHalf = x.substring(percentDetected + 1, x.length());
                            System.out.println("laterhalf " + laterHalf);
                            switchValue = 1;
                        }
                        switch (switchValue) {
                            case 1:
                                if (dst[i] == '+' || dst[i] == '-' || dst[i] == '*' || dst[i] == '/' || dst[i] == '(' || dst[i] == ')') {
                                    variableDetected = i;
                                    String firstHalf = x.substring(0, (variableDetected + 1));
                                    System.out.println("firsthalf " + firstHalf);
                                    String mainValue = x.substring(variableDetected + 1, percentDetected);
                                    System.out.println("mainvalue " + mainValue);
                                    toBeCalculated = firstHalf + "(" + mainValue + "/100" + ")" + laterHalf;
                                    System.out.println("result " + toBeCalculated);
                                } else if (Long.parseLong(x.substring(0, percentDetected)) <= Long.MAX_VALUE) {  // FAULTY
                                    toBeCalculated = x.substring(0, percentDetected) + "/100";
                                }
                                break;
                            case 2:
                                break;
                        }
                    }
                    x = toBeCalculated;
                } //=============================================== PERCENTAGE METHOD

                String newx = String.valueOf(eng.eval(toBeCalculated)); // TAKE OUTSIDE
                jTextArea1.setText(newx);

            } else {
                toBeCalculated = jTextArea1.getText();
                // =============================================== PERCENTAGE METHOD BELOW
                String x = jTextArea1.getText();
                while (x.contains("%")) {
                    System.out.println("entered");
                    char[] dst = new char[x.length()];
                    x.getChars(0, x.length(), dst, 0);

                    int percentDetected = 0;
                    int variableDetected = 0;
                    int switchValue = 2;
                    String laterHalf = null;

                    for (int i = x.length() - 1; i >= 0; i--) {
                        if (dst[i] == '%') {
                            percentDetected = i;
                            laterHalf = x.substring(percentDetected + 1, x.length());
                            System.out.println("laterhalf " + laterHalf);
                            switchValue = 1;
                        }
                        switch (switchValue) {
                            case 1:
                                if (dst[i] == '+' || dst[i] == '-' || dst[i] == '*' || dst[i] == '/' || dst[i] == '(' || dst[i] == ')') {
                                    variableDetected = i;
                                    String firstHalf = x.substring(0, (variableDetected + 1));
                                    System.out.println("firsthalf " + firstHalf);
                                    String mainValue = x.substring(variableDetected + 1, percentDetected);
                                    System.out.println("mainvalue " + mainValue);
                                    toBeCalculated = firstHalf + "(" + mainValue + "/100" + ")" + laterHalf;
                                    System.out.println("result " + toBeCalculated);
                                } else if (Long.parseLong(x.substring(0, percentDetected)) <= Long.MAX_VALUE) {
                                    toBeCalculated = "(" + x.substring(0, percentDetected) + "/100" + ")";
                                }
                                break;
                            case 2:
                                break;
                        }
                    }
                    x = toBeCalculated;
                } //=============================================== PERCENTAGE METHOD

                String newx = String.valueOf(eng.eval(toBeCalculated));
                jTextArea1.setText(newx);
            }
        } catch (ScriptException ex) {
            jTextArea1.setText("Syntax_Error");
        }


    }//GEN-LAST:event_btnEqualMouseClicked

    private void btnPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/') {
            jTextArea1.setText(jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1) + "+");
        } else {
            if (jTextArea1.getText().equalsIgnoreCase("0")) {
                jTextArea1.setText("+");
            } else {
                jTextArea1.setText(jTextArea1.getText() + "+");
            }
        }


    }//GEN-LAST:event_btnPlusMouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("1");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "1");
        }
    }//GEN-LAST:event_btn1MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("4");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "4");
        }
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("5");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "5");
        }
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("6");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "6");
        }
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("7");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "7");
        }
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("8");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "8");
        }
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("9");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "9");
        }
    }//GEN-LAST:event_btn9MouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText("0");
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/') {
            jTextArea1.setText(jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1) + "*");
        } else {
            if (jTextArea1.getText().equalsIgnoreCase("0")) {
                jTextArea1.setText("*");
            } else {
                jTextArea1.setText(jTextArea1.getText() + "*");
            }
        }
    }//GEN-LAST:event_btnMultiplyMouseClicked

    private void btnMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/') {
            jTextArea1.setText(jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1) + "-");
        } else {
            if (jTextArea1.getText().equalsIgnoreCase("0")) {
                jTextArea1.setText("-");
            } else {
                jTextArea1.setText(jTextArea1.getText() + "-");
            }
        }
    }//GEN-LAST:event_btnMinusMouseClicked

    private void btnDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().contains(".")) {

        } else {
            if (jTextArea1.getText().equalsIgnoreCase("0")) {
                jTextArea1.setText(".");
            } else {
                jTextArea1.setText(jTextArea1.getText() + ".");
            }
        }
        //================================================================= DOUBLE DOTS
        char[] dst = new char[jTextArea1.getText().length()];
        jTextArea1.getText().getChars(0, jTextArea1.getText().length(), dst, 0);

        for (int i = jTextArea1.getText().length() - 1; i >= 0; i--) {
            if (dst[i] == '+') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains(".")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + ".");
                }
            } else if (dst[i] == '-') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains(".")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + ".");
                }
            } else if (dst[i] == '*') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains(".")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + ".");
                }
            } else if (dst[i] == '/') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains(".")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + ".");
                }
            } else if (dst[i] == '(') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains(".")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + ".");
                }
            } else if (dst[i] == ')') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains(".")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + ".");
                }
            }
        }
    }//GEN-LAST:event_btnDotMouseClicked

    private void btnReciprocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReciprocalMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("0");
        } else {
            if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '.') {
                String recip = (jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1));
                String flip = "1/" + "(" + recip + ")";
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine eng = mgr.getEngineByName("JavaScript");
                try {
                    String newx = String.valueOf(eng.eval(flip));
                    jTextArea1.setText(newx);
                } catch (ScriptException ex) {
                    Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine eng = mgr.getEngineByName("JavaScript");
                String newx;
                try {
                    newx = String.valueOf(eng.eval("1/" + "(" + jTextArea1.getText() + ")"));
                    jTextArea1.setText(newx);
                } catch (ScriptException ex) {
                    Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }

    }//GEN-LAST:event_btnReciprocalMouseClicked

    private void btnBackSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackSpaceMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText(jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1));
    }//GEN-LAST:event_btnBackSpaceMouseClicked

    private void btnPlusMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMinusMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("0");
        }
        if (!(jTextArea1.getText().equalsIgnoreCase("0"))) {
            if (jTextArea1.getText().charAt(0) == '-') {
                jTextArea1.setText(jTextArea1.getText().substring(1));
            } else {
                jTextArea1.setText("-" + jTextArea1.getText());
            }
        }

    }//GEN-LAST:event_btnPlusMinusMouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("0");
        } else {
            jTextArea1.setText(jTextArea1.getText() + "0");
        }
    }//GEN-LAST:event_btn0MouseClicked

    private void btnDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/') {
            jTextArea1.setText(jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1) + "/");
        } else {
            if (jTextArea1.getText().equalsIgnoreCase("0")) {
                jTextArea1.setText("/");
            } else {
                jTextArea1.setText(jTextArea1.getText() + "/");
            }
        }
    }//GEN-LAST:event_btnDivisionMouseClicked

    private void btnSquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSquareMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("0");
        } else {
            if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '.') {
                String recip = (jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1));
                String flip = recip + "*" + recip;
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine eng = mgr.getEngineByName("JavaScript");
                try {
                    String newx = String.valueOf(eng.eval(flip));
                    jTextArea1.setText(newx);
                } catch (ScriptException ex) {
                    Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine eng = mgr.getEngineByName("JavaScript");
                String newx;
                try {
                    newx = String.valueOf(eng.eval(jTextArea1.getText() + "*" + jTextArea1.getText()));
                    jTextArea1.setText(newx);
                } catch (ScriptException ex) {
                    Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnSquareMouseClicked

    private void btnSqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSqrtMouseClicked
        // TODO add your handling code here:
        if (jTextArea1.getText().charAt(0) == '-') {
            jTextArea1.setText("Syntax Error");
        }

        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("0");
        } else {
            if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '.') {
                String recip = (jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1));
                String flip = recip;

                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine eng = mgr.getEngineByName("JavaScript");
                try {
                    String newx = String.valueOf(eng.eval(flip));
                    double sqr = Math.sqrt(Double.parseDouble(newx));
                    String strAgain = String.valueOf(sqr);
                    jTextArea1.setText(strAgain);
                } catch (ScriptException ex) {
                    ex.printStackTrace();
                }
            } else {
                ScriptEngineManager mgr = new ScriptEngineManager();
                ScriptEngine eng = mgr.getEngineByName("JavaScript");
                String newx;
                try {
                    newx = String.valueOf(eng.eval((jTextArea1.getText())));
                    double sqr = Math.sqrt(Double.parseDouble(newx));
                    String strAgain = String.valueOf(sqr);
                    jTextArea1.setText(strAgain);
                } catch (ScriptException ex) {
                    ex.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_btnSqrtMouseClicked

    private void btnPercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercentMouseClicked
        // TODO add your handling code here:
//        if (jTextArea1.getText().charAt(0) == '-') {
//            jTextArea1.setText("Syntax Error");
//        }
//
//        if (jTextArea1.getText().equalsIgnoreCase("0")) {
//            jTextArea1.setText("0");
//        } else {
//            if (jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '+' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '-' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '*' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '/' || jTextArea1.getText().charAt(jTextArea1.getText().length() - 1) == '.') {
//                String recip = (jTextArea1.getText().substring(0, jTextArea1.getText().length() - 1));
//                String flip = "(" + recip + ")" + "/100";
//
//                ScriptEngineManager mgr = new ScriptEngineManager();
//                ScriptEngine eng = mgr.getEngineByName("JavaScript");
//                try {
//                    String newx = String.valueOf(eng.eval(flip));
//                    jTextArea1.setText(newx);
//                } catch (ScriptException ex) {
//                    ex.printStackTrace();
//                }
//            } else {
//                ScriptEngineManager mgr = new ScriptEngineManager();
//                ScriptEngine eng = mgr.getEngineByName("JavaScript");
//                String newx;
//                try {
//                    newx = String.valueOf(eng.eval(("(" + jTextArea1.getText() + ")" + "/100")));
//                    String strAgain = String.valueOf(newx);
//                    jTextArea1.setText(strAgain);
//                } catch (ScriptException ex) {
//                    ex.printStackTrace();
//                }
//
//            }
//        }
        if (jTextArea1.getText().contains("%")) {

        } else {
            jTextArea1.setText(jTextArea1.getText() + "%");
        }
        //================================================================= DOUBLE PERCENTAGE SIGN
        char[] dst = new char[jTextArea1.getText().length()];
        jTextArea1.getText().getChars(0, jTextArea1.getText().length(), dst, 0);

        for (int i = jTextArea1.getText().length() - 1; i >= 0; i--) {
            if (dst[i] == '+') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains("%")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + "%");
                }
            } else if (dst[i] == '-') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains("%")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + "%");
                }
            } else if (dst[i] == '*') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains("%")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + "%");
                }
            } else if (dst[i] == '/') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains("%")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + "%");
                }
            } else if (dst[i] == '(') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains("%")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + "%");
                }
            } else if (dst[i] == ')') {
                int x = i;
                String sub = jTextArea1.getText().substring(x, jTextArea1.getText().length());
                if (sub.contains("%")) {

                } else {
                    jTextArea1.setText(jTextArea1.getText() + "%");
                }
            }
        }
    }//GEN-LAST:event_btnPercentMouseClicked

    private void btnBracketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBracketsMouseClicked
        // TODO add your handling code here:
        int countOpen = 0;
        int countClose = 0;

        if (jTextArea1.getText().equalsIgnoreCase("0")) {
            jTextArea1.setText("(");

        } else if (!(jTextArea1.getText().contains("("))) {
            jTextArea1.setText(jTextArea1.getText() + "(");
            System.out.println("1");

        } else {
            char[] dest = new char[jTextArea1.getText().length()];
            jTextArea1.getText().getChars(0, jTextArea1.getText().length(), dest, 0);
            for (char i : dest) {
                if (i == '(') {
                    countOpen++;
                }
                if (i == ')') {
                    countClose++;
                }
                System.out.println(i);
            }
            System.out.print(countOpen + " ");
            System.out.print(countClose + " ");
            if (countOpen > countClose) {
                jTextArea1.setText(jTextArea1.getText() + ")");
                System.out.println("2");
            } else if (countOpen == countClose) {
                jTextArea1.setText(jTextArea1.getText() + "(");
                System.out.println("3");
            }
        }

    }//GEN-LAST:event_btnBracketsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Calculator().setVisible(true);
                } catch (ScriptException ex) {
                    Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBackSpace;
    private javax.swing.JButton btnBrackets;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnReciprocal;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSquare;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
